#!/usr/bin/env python3
"""Sync upcoming Luma events into data/events.json.

Uses Luma's public calendar JSON endpoint (no auth required for public calendars).
Writes a normalized shape consumed by js/events.js.
"""
from __future__ import annotations

import json
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

CALENDAR_ID = "cal-y1buynLYVuwNXQN"
LIMIT = 12
API = (
    "https://api.lu.ma/calendar/get-items"
    f"?calendar_api_id={CALENDAR_ID}&period=future&pagination_limit={LIMIT}"
)
OUT = Path(__file__).resolve().parent.parent / "data" / "events.json"


def fetch() -> dict:
    req = urllib.request.Request(
        API,
        headers={
            "User-Agent": "mlnomads-events-sync/1.0 (+https://mlnomads.com)",
            "Accept": "application/json",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())


def classify(event: dict) -> str:
    name = (event.get("name") or "").lower()
    if any(k in name for k in ("hackathon", "buildthon", "build-a-thon")):
        return "hackathon"
    if any(k in name for k in ("workshop", "tutorial", "lab")):
        return "workshop"
    if any(k in name for k in ("paper", "reading", "discussion", "talk", "ama")):
        return "talk"
    if any(k in name for k in ("meetup", "social", "office hours")):
        return "meetup"
    return "event"


def format_date(iso: str, tz: str | None) -> str:
    """ISO UTC → 'May 30, 2026' (or with weekday if useful)."""
    if not iso:
        return ""
    dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
    return dt.strftime("%b %-d, %Y")


def location_blurb(event: dict) -> str:
    location_type = event.get("location_type")
    if location_type == "virtual" or event.get("virtual_info"):
        return "Online"
    geo = event.get("geo_address_info") or {}
    city = geo.get("city")
    if city:
        return city
    return ""


def normalize(entry: dict) -> dict:
    event = entry.get("event", {})
    url_slug = event.get("url", "")
    api_id = event.get("api_id", "")
    return {
        "id": api_id,
        "title": event.get("name", "Untitled event"),
        "date": format_date(event.get("start_at"), event.get("timezone")),
        "start_at": event.get("start_at"),
        "type": classify(event),
        "location": location_blurb(event),
        "image": event.get("cover_url") or event.get("social_image_url") or "",
        "link": f"https://lu.ma/{url_slug}" if url_slug else "https://lu.ma/mlnomads",
    }


def main() -> int:
    try:
        payload = fetch()
    except Exception as exc:
        print(f"sync_luma: fetch failed: {exc}", file=sys.stderr)
        return 1

    entries = payload.get("entries") or []
    events = [normalize(e) for e in entries]
    events.sort(key=lambda e: e.get("start_at") or "")

    out = {
        "_comment": (
            "Auto-generated by scripts/sync_luma.py from "
            f"https://lu.ma/mlnomads (calendar {CALENDAR_ID}). "
            "Do not edit by hand — changes will be overwritten."
        ),
        "synced_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "https://lu.ma/mlnomads",
        "events": events,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    print(f"sync_luma: wrote {len(events)} event(s) to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
